Add optional camera "Latest PTZ" tooltip
mnit-rtmc/iris pull request #127
Opened 2024-04-01 22:51 UTC by gordonparikh

This adds tracking of camera PTZ events/users for display in the camera tooltip, with functionality controlled by a system attribute. Note that the system attribute is currently added to the database by a separate SQL script that should be merged into the desired migrate script.

2024-04-02 14:54 UTC, DougLau requested changes

2024-04-02 14:54 UTC, DougLau commented on src/us/mn/state/dot/tms/client/camera/CameraTheme.java
> +import us.mn.state.dot.tms.WeatherSensor;
Unused

2024-04-02 14:57 UTC, DougLau commented on src/us/mn/state/dot/tms/server/CameraImpl.java
> +		notifyAttribute("ptzUser");
Check system attribute before notifying

2024-04-08 22:16 UTC, gordonparikh commented
I made the changes you requested and tested it quick to double check it works as expected. Let me know if you have any other comments.

2024-04-09 12:41 UTC, merged